#!/bin/bash
# Start development servers

echo "==================================="
echo "Link-in-Bio Development"
echo "==================================="
echo ""
echo "Start servers manually in separate terminals:"
echo ""
echo "Terminal 1 - API (Go Fiber):"
echo "  cd apps/api && go run cmd/api/main.go"
echo ""
echo "Terminal 2 - Web (SvelteKit):"
echo "  cd apps/web && npm install && npm run dev"
echo ""
echo "==================================="
echo "URLs:"
echo "  API:  http://localhost:8080"
echo "  Web:  http://localhost:5173"
echo "  Health: http://localhost:8080/health"
echo "==================================="
